# Generated by Django 4.0.4 on 2023-01-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('description', models.TextField(null=True)),
                ('example', models.CharField(max_length=250, null=True)),
                ('date_of_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Grammer',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='grammer',
            index=models.Index(fields=['date_of_created', 'example', 'text'], name='Grammer_date_of_cebebc_idx'),
        ),
    ]
